#ifndef CONSTANTESBOUTON_H
#define CONSTANTESBOUTON_H


#include <SDL/SDL.h>

//!
//! Constantes des boutons dans la feuille de sprite
//! \author pgutierrez
//! \date 11/11/16
//! \version 0.1
//!

const SDL_Color COULEUR_BOUTON_CLIQUABLE = {0, 0, 0, 255};
const SDL_Color COULEUR_BOUTON_NON_CLIQUABLE = {150, 150, 150, 255};

const int COORD_X_BOUTON_NORMAL = 0;
const int COORD_Y_BOUTON_NORMAL = 0;
const int WIDTH_BOUTON_NORMAL = 244;
const int HEIGHT_BOUTON_NORMAL = 49;

const int COORD_X_BOUTON_ONGLET = 0;
const int COORD_Y_BOUTON_ONGLET = 0;
const int WIDTH_BOUTON_ONGLET = 244;
const int HEIGHT_BOUTON_ONGLET = 49;

const int COORD_X_BOUTON_SELECTEUR_ACTIF = 0;
const int COORD_Y_BOUTON_SELECTEUR_ACTIF = 0;
const int WIDTH_BOUTON_SELECTEUR_ACTIF = 244;
const int HEIGHT_BOUTON_SELECTEUR_ACTIF = 49;

const int COORD_X_BOUTON_SELECTEUR_INACTIF = 0;
const int COORD_Y_BOUTON_SELECTEUR_INACTIF = 0;
const int WIDTH_BOUTON_SELECTEUR_INACTIF = 244;
const int HEIGHT_BOUTON_SELECTEUR_INACTIF = 49;

const int COORD_X_BOUTON_NORMAL_ACTIF = 0;
const int COORD_Y_BOUTON_NORMAL_ACTIF = 64;
const int WIDTH_BOUTON_NORMAL_ACTIF = 244;
const int HEIGHT_BOUTON_NORMAL_ACTIF = 49;


#endif // CONSTANTESBOUTON_H
